export type Property = {
  id: string;
  title: string;
  description: string;
  location: string;
  price: number;
  roomType: 'shared' | 'private';
  imageUrl: string;
  amenities: string[];
  available: boolean;
  nearbyFacilities: string[];
  ownerContact: string;
  virtualTourUrl?: string;
};

export type RoommateProfile = {
  id: string;
  name: string;
  age: number;
  gender: string;
  occupation: string;
  avatar: string;
  bio: string;
  budget: number;
  location: string;
  preferences: {
    sleepingHabits: string;
    cleanliness: string;
    socialHabits: string;
    smoking: string;
    drinking: string;
    schedule: string;
    noiseTolerance: string;
    diet: string;
    pets: string;
    security: string;
  };
  compatibilityScores: {
    [userId: string]: number;
  };
};

export const sampleProperties: Property[] = [
  {
    id: '1',
    title: 'Modern Studio Apartment',
    description: 'Bright and airy studio apartment with modern amenities and great views.',
    location: 'Downtown, New York',
    price: 1200,
    roomType: 'private',
    imageUrl: 'https://images.unsplash.com/photo-1524230572899-a752b3835840',
    amenities: ['WiFi', 'Gym', 'Laundry', 'Security'],
    available: true,
    nearbyFacilities: ['Metro Station', 'University', 'Shopping Mall'],
    ownerContact: 'owner1@example.com',
    virtualTourUrl: 'https://example.com/virtual-tour/1',
  },
  {
    id: '2',
    title: 'Cozy Shared Apartment',
    description: 'Furnished shared room in a friendly apartment with all utilities included.',
    location: 'Brooklyn, New York',
    price: 800,
    roomType: 'shared',
    imageUrl: 'https://images.unsplash.com/photo-1487958449943-2429e8be8625',
    amenities: ['WiFi', 'Kitchen', 'Heating', 'Cooling'],
    available: true,
    nearbyFacilities: ['Park', 'Grocery Store', 'Bus Stop'],
    ownerContact: 'owner2@example.com',
  },
  {
    id: '3',
    title: 'Luxury Private Room',
    description: 'Private room in a luxury apartment with access to all amenities.',
    location: 'Manhattan, New York',
    price: 1500,
    roomType: 'private',
    imageUrl: 'https://images.unsplash.com/photo-1472396961693-142e6e269027',
    amenities: ['WiFi', 'Pool', 'Gym', 'Parking', 'Security'],
    available: true,
    nearbyFacilities: ['Metro Station', 'Office Hub', 'Shopping Mall'],
    ownerContact: 'owner3@example.com',
    virtualTourUrl: 'https://example.com/virtual-tour/3',
  },
  {
    id: '4',
    title: 'Student-Friendly Shared Space',
    description: 'Affordable shared room perfect for students, close to university.',
    location: 'Queens, New York',
    price: 600,
    roomType: 'shared',
    imageUrl: 'https://images.unsplash.com/photo-1521128591876-b4ace034003a',
    amenities: ['WiFi', 'Study Area', 'Laundry'],
    available: true,
    nearbyFacilities: ['University', 'Library', 'Cafes'],
    ownerContact: 'owner4@example.com',
  },
  {
    id: '5',
    title: 'Quiet Private Room Near Park',
    description: 'Peaceful private room in a well-maintained house near Central Park.',
    location: 'Upper West Side, New York',
    price: 1300,
    roomType: 'private',
    imageUrl: 'https://images.unsplash.com/photo-1558976825-6b1b03a03719',
    amenities: ['WiFi', 'AC', 'Heating', 'Garden', 'Laundry'],
    available: true,
    nearbyFacilities: ['Central Park', 'Museum', 'Restaurants'],
    ownerContact: 'owner5@example.com',
  },
  {
    id: '6',
    title: 'Trendy Brooklyn Shared Apartment',
    description: 'Hip shared apartment in the heart of Brooklyn with artistic roommates.',
    location: 'Williamsburg, Brooklyn',
    price: 950,
    roomType: 'shared',
    imageUrl: 'https://images.unsplash.com/photo-1554995207-c18c203602cb',
    amenities: ['WiFi', 'Rooftop', 'Laundry', 'Bike Storage'],
    available: true,
    nearbyFacilities: ['Art Galleries', 'Bars', 'Subway'],
    ownerContact: 'owner6@example.com',
  },
  {
    id: '7',
    title: 'Upscale Private Room in Condo',
    description: 'Luxury private room in a modern condo with doorman and amenities.',
    location: 'Financial District, New York',
    price: 1800,
    roomType: 'private',
    imageUrl: 'https://images.unsplash.com/photo-1556912167-f556f1f39fdf',
    amenities: ['WiFi', 'Gym', 'Pool', 'Doorman', '24/7 Security'],
    available: true,
    nearbyFacilities: ['Wall Street', 'Restaurants', 'Shopping'],
    ownerContact: 'owner7@example.com',
    virtualTourUrl: 'https://example.com/virtual-tour/7',
  },
  {
    id: '8',
    title: 'Cozy Shared Room for Students',
    description: 'Affordable shared room ideal for students or young professionals.',
    location: 'Astoria, Queens',
    price: 750,
    roomType: 'shared',
    imageUrl: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5',
    amenities: ['WiFi', 'Utilities Included', 'Shared Kitchen', 'Laundry'],
    available: true,
    nearbyFacilities: ['University', 'Subway', 'Parks'],
    ownerContact: 'owner8@example.com',
  },
  {
    id: '9',
    title: 'Sunny Private Room in Brownstone',
    description: 'Charming private room in a historic brownstone with large windows.',
    location: 'Park Slope, Brooklyn',
    price: 1400,
    roomType: 'private',
    imageUrl: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb',
    amenities: ['WiFi', 'Laundry', 'Heating', 'Garden Access'],
    available: true,
    nearbyFacilities: ['Prospect Park', 'Restaurants', 'Subway'],
    ownerContact: 'owner9@example.com',
  },
  {
    id: '10',
    title: 'Budget-Friendly Shared Room',
    description: 'Economical shared room option with all basics covered.',
    location: 'Washington Heights, Manhattan',
    price: 600,
    roomType: 'shared',
    imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
    amenities: ['WiFi', 'Shared Bathroom', 'Kitchen Access'],
    available: true,
    nearbyFacilities: ['Columbia University', 'Parks', 'Grocery Stores'],
    ownerContact: 'owner10@example.com',
  },
  {
    id: '11',
    title: 'Modern Private Room in New Building',
    description: 'Sleek private room in a newly constructed building with modern amenities.',
    location: 'Long Island City, Queens',
    price: 1600,
    roomType: 'private',
    imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85',
    amenities: ['WiFi', 'Gym', 'Rooftop', 'In-unit Laundry', 'Parking'],
    available: true,
    nearbyFacilities: ['Subway', 'Restaurants', 'Waterfront'],
    ownerContact: 'owner11@example.com',
    virtualTourUrl: 'https://example.com/virtual-tour/11',
  },
  {
    id: '12',
    title: 'Comfortable Shared Space in Townhouse',
    description: 'Well-maintained shared room in a quiet townhouse with garden access.',
    location: 'Harlem, Manhattan',
    price: 850,
    roomType: 'shared',
    imageUrl: 'https://images.unsplash.com/photo-1560185007-5f0bb1866cab',
    amenities: ['WiFi', 'Garden', 'Laundry', 'Kitchen'],
    available: true,
    nearbyFacilities: ['Apollo Theater', 'Parks', 'Subway'],
    ownerContact: 'owner12@example.com',
  },
  {
    id: '13',
    title: 'Spacious Private Room in Loft',
    description: 'Large private room in an artist loft with high ceilings and great light.',
    location: 'Bushwick, Brooklyn',
    price: 1100,
    roomType: 'private',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f',
    amenities: ['WiFi', 'Art Studio', 'Laundry', 'Rooftop Access'],
    available: true,
    nearbyFacilities: ['Art Galleries', 'Cafes', 'Subway'],
    ownerContact: 'owner13@example.com',
  },
  {
    id: '14',
    title: 'Eco-Friendly Shared Living Space',
    description: 'Environmentally conscious shared living with like-minded roommates.',
    location: 'Greenpoint, Brooklyn',
    price: 900,
    roomType: 'shared',
    imageUrl: 'https://images.unsplash.com/photo-1494526585095-c41cabfe98b2',
    amenities: ['WiFi', 'Composting', 'Garden', 'Bike Storage', 'Solar Power'],
    available: true,
    nearbyFacilities: ['Parks', 'Farmers Market', 'Organic Stores'],
    ownerContact: 'owner14@example.com',
  },
  {
    id: '15',
    title: 'Private Room with River View',
    description: 'Stunning private room with Hudson River views in luxury building.',
    location: 'Chelsea, Manhattan',
    price: 1950,
    roomType: 'private',
    imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688',
    amenities: ['WiFi', 'Gym', 'Pool', 'Doorman', 'Laundry'],
    available: true,
    nearbyFacilities: ['High Line', 'Art Galleries', 'Restaurants'],
    ownerContact: 'owner15@example.com',
    virtualTourUrl: 'https://example.com/virtual-tour/15',
  },
  {
    id: '16',
    title: 'Budget Shared Room for Students',
    description: 'Affordable shared room designed for students on a budget.',
    location: 'Bronx, New York',
    price: 550,
    roomType: 'shared',
    imageUrl: 'https://images.unsplash.com/photo-1596204976717-1a9ff47d74e8',
    amenities: ['WiFi', 'Desk', 'Shared Kitchen'],
    available: true,
    nearbyFacilities: ['University', 'Library', 'Parks'],
    ownerContact: 'owner16@example.com',
  },
  {
    id: '17',
    title: 'Private Room in Historic Building',
    description: 'Elegant private room in a beautifully restored historic building.',
    location: 'Upper East Side, Manhattan',
    price: 1700,
    roomType: 'private',
    imageUrl: 'https://images.unsplash.com/photo-1540518614846-7eded433c457',
    amenities: ['WiFi', 'Elevator', 'Laundry', 'Doorman'],
    available: true,
    nearbyFacilities: ['Museums', 'Central Park', 'Shopping'],
    ownerContact: 'owner17@example.com',
  },
  {
    id: '18',
    title: 'Shared Room in Social House',
    description: 'Fun shared room in a house known for social events and friendly roommates.',
    location: 'Ridgewood, Queens',
    price: 700,
    roomType: 'shared',
    imageUrl: 'https://images.unsplash.com/photo-1536376072261-38c75010e6c9',
    amenities: ['WiFi', 'Backyard', 'BBQ', 'Laundry'],
    available: true,
    nearbyFacilities: ['Bars', 'Parks', 'Subway'],
    ownerContact: 'owner18@example.com',
  },
  {
    id: '19',
    title: 'Minimalist Private Room',
    description: 'Clean, minimalist private room perfect for professionals.',
    location: 'Battery Park, Manhattan',
    price: 1500,
    roomType: 'private',
    imageUrl: 'https://images.unsplash.com/photo-1536399646555-27b516a1f307',
    amenities: ['WiFi', 'Gym', 'Waterfront Access', 'Security'],
    available: true,
    nearbyFacilities: ['Financial District', 'Waterfront', 'Shopping'],
    ownerContact: 'owner19@example.com',
  },
  {
    id: '20',
    title: 'Creative Shared Space',
    description: 'Vibrant shared living in a house full of artists and musicians.',
    location: 'Bed-Stuy, Brooklyn',
    price: 800,
    roomType: 'shared',
    imageUrl: 'https://images.unsplash.com/photo-1574873215043-44119461cb3b',
    amenities: ['WiFi', 'Music Room', 'Art Studio', 'Backyard'],
    available: true,
    nearbyFacilities: ['Music Venues', 'Art Spaces', 'Cafes'],
    ownerContact: 'owner20@example.com',
  },
];

export const sampleRoommates: RoommateProfile[] = [
  {
    id: '1',
    name: 'Alex Johnson',
    age: 25,
    gender: 'Male',
    occupation: 'Software Engineer',
    avatar: 'https://i.pravatar.cc/150?img=11',
    bio: 'Tech enthusiast who enjoys coding and gaming. Looking for a quiet place to live and work.',
    budget: 1200,
    location: 'New York',
    preferences: {
      sleepingHabits: 'Night Owl',
      cleanliness: 'Very Neat',
      socialHabits: 'Introvert',
      smoking: 'Non-smoker',
      drinking: 'Occasional',
      schedule: 'Work from home',
      noiseTolerance: 'Low',
      diet: 'No Preference',
      pets: 'No Pets',
      security: 'High Priority',
    },
    compatibilityScores: {},
  },
  {
    id: '2',
    name: 'Samantha Lee',
    age: 28,
    gender: 'Female',
    occupation: 'Marketing Manager',
    avatar: 'https://i.pravatar.cc/150?img=5',
    bio: 'Creative professional looking for a place with good vibes and friendly roommates.',
    budget: 1000,
    location: 'New York',
    preferences: {
      sleepingHabits: 'Early Riser',
      cleanliness: 'Neat',
      socialHabits: 'Extrovert',
      smoking: 'Non-smoker',
      drinking: 'Social Drinker',
      schedule: 'Regular 9-5',
      noiseTolerance: 'Medium',
      diet: 'Vegetarian',
      pets: 'Loves Pets',
      security: 'Medium Priority',
    },
    compatibilityScores: {},
  },
  {
    id: '3',
    name: 'Marcus Chen',
    age: 23,
    gender: 'Male',
    occupation: 'Graduate Student',
    avatar: 'https://i.pravatar.cc/150?img=7',
    bio: 'PhD student looking for quiet space to study and relax. Clean and respectful roommate.',
    budget: 800,
    location: 'New York',
    preferences: {
      sleepingHabits: 'Night Owl',
      cleanliness: 'Very Neat',
      socialHabits: 'Balanced',
      smoking: 'Non-smoker',
      drinking: 'Occasional',
      schedule: 'Student Schedule',
      noiseTolerance: 'Low',
      diet: 'No Preference',
      pets: 'No Pets',
      security: 'High Priority',
    },
    compatibilityScores: {},
  },
  {
    id: '4',
    name: 'Priya Sharma',
    age: 26,
    gender: 'Female',
    occupation: 'Nurse',
    avatar: 'https://i.pravatar.cc/150?img=3',
    bio: 'Healthcare professional with rotating shifts. Quiet, clean, and respectful of shared spaces.',
    budget: 1100,
    location: 'New York',
    preferences: {
      sleepingHabits: 'Varies due to shifts',
      cleanliness: 'Very Neat',
      socialHabits: 'Introvert',
      smoking: 'Non-smoker',
      drinking: 'Rarely',
      schedule: 'Rotating Shifts',
      noiseTolerance: 'Medium',
      diet: 'Vegetarian',
      pets: 'OK with pets',
      security: 'High Priority',
    },
    compatibilityScores: {},
  },
  {
    id: '5',
    name: 'Jordan Williams',
    age: 30,
    gender: 'Male',
    occupation: 'Graphic Designer',
    avatar: 'https://i.pravatar.cc/150?img=12',
    bio: 'Creative designer who works from home and enjoys cooking. Looking for a chill environment.',
    budget: 1300,
    location: 'Brooklyn',
    preferences: {
      sleepingHabits: 'Regular Hours',
      cleanliness: 'Neat',
      socialHabits: 'Balanced',
      smoking: 'Outside Only',
      drinking: 'Social Drinker',
      schedule: 'Flexible',
      noiseTolerance: 'Medium',
      diet: 'No Preference',
      pets: 'Loves Pets',
      security: 'Medium Priority',
    },
    compatibilityScores: {},
  },
  {
    id: '6',
    name: 'Emma Rodriguez',
    age: 24,
    gender: 'Female',
    occupation: 'Elementary Teacher',
    avatar: 'https://i.pravatar.cc/150?img=9',
    bio: 'Teacher who loves reading and quiet evenings. Early riser and organized.',
    budget: 950,
    location: 'Queens',
    preferences: {
      sleepingHabits: 'Early Riser',
      cleanliness: 'Very Neat',
      socialHabits: 'Introvert',
      smoking: 'Non-smoker',
      drinking: 'Rarely',
      schedule: 'Regular 9-5',
      noiseTolerance: 'Low',
      diet: 'No Preference',
      pets: 'OK with pets',
      security: 'High Priority',
    },
    compatibilityScores: {},
  },
  {
    id: '7',
    name: 'Tyler Jackson',
    age: 27,
    gender: 'Male',
    occupation: 'Financial Analyst',
    avatar: 'https://i.pravatar.cc/150?img=8',
    bio: 'Finance professional who enjoys fitness and sports. Clean, organized, and respectful.',
    budget: 1400,
    location: 'Manhattan',
    preferences: {
      sleepingHabits: 'Early Riser',
      cleanliness: 'Very Neat',
      socialHabits: 'Balanced',
      smoking: 'Non-smoker',
      drinking: 'Social Drinker',
      schedule: 'Regular 9-5',
      noiseTolerance: 'Medium',
      diet: 'No Preference',
      pets: 'No Pets',
      security: 'High Priority',
    },
    compatibilityScores: {},
  },
  {
    id: '8',
    name: 'Zoe Chen',
    age: 22,
    gender: 'Female',
    occupation: 'Music Student',
    avatar: 'https://i.pravatar.cc/150?img=1',
    bio: 'Music conservatory student who practices during the day. Friendly and tidy.',
    budget: 800,
    location: 'Manhattan',
    preferences: {
      sleepingHabits: 'Regular Hours',
      cleanliness: 'Neat',
      socialHabits: 'Extrovert',
      smoking: 'Non-smoker',
      drinking: 'Social Drinker',
      schedule: 'Student Schedule',
      noiseTolerance: 'High',
      diet: 'Vegetarian',
      pets: 'Loves Pets',
      security: 'Medium Priority',
    },
    compatibilityScores: {},
  },
  {
    id: '9',
    name: 'Miguel Santos',
    age: 31,
    gender: 'Male',
    occupation: 'Chef',
    avatar: 'https://i.pravatar.cc/150?img=13',
    bio: 'Professional chef who works late nights. Loves to cook at home and share meals.',
    budget: 1100,
    location: 'Brooklyn',
    preferences: {
      sleepingHabits: 'Night Owl',
      cleanliness: 'Neat',
      socialHabits: 'Extrovert',
      smoking: 'Outside Only',
      drinking: 'Social Drinker',
      schedule: 'Evening Shifts',
      noiseTolerance: 'High',
      diet: 'No Preference',
      pets: 'OK with pets',
      security: 'Medium Priority',
    },
    compatibilityScores: {},
  },
  {
    id: '10',
    name: 'Olivia Kim',
    age: 26,
    gender: 'Female',
    occupation: 'UX Designer',
    avatar: 'https://i.pravatar.cc/150?img=6',
    bio: 'Designer who enjoys photography and hiking on weekends. Looking for respectful roommates.',
    budget: 1250,
    location: 'Manhattan',
    preferences: {
      sleepingHabits: 'Regular Hours',
      cleanliness: 'Very Neat',
      socialHabits: 'Balanced',
      smoking: 'Non-smoker',
      drinking: 'Occasional',
      schedule: 'Regular 9-5',
      noiseTolerance: 'Medium',
      diet: 'No Preference',
      pets: 'No Pets',
      security: 'High Priority',
    },
    compatibilityScores: {},
  },
  {
    id: '11',
    name: 'Lucas Washington',
    age: 29,
    gender: 'Male',
    occupation: 'Attorney',
    avatar: 'https://i.pravatar.cc/150?img=14',
    bio: 'Lawyer who works long hours and values quiet time at home. Neat and organized.',
    budget: 1600,
    location: 'Manhattan',
    preferences: {
      sleepingHabits: 'Regular Hours',
      cleanliness: 'Very Neat',
      socialHabits: 'Introvert',
      smoking: 'Non-smoker',
      drinking: 'Occasional',
      schedule: 'Long Hours',
      noiseTolerance: 'Low',
      diet: 'No Preference',
      pets: 'No Pets',
      security: 'High Priority',
    },
    compatibilityScores: {},
  },
  {
    id: '12',
    name: 'Sophia Patel',
    age: 25,
    gender: 'Female',
    occupation: 'Medical Resident',
    avatar: 'https://i.pravatar.cc/150?img=4',
    bio: 'Medical resident with irregular hours. Quiet, clean, and considerate roommate.',
    budget: 1300,
    location: 'Queens',
    preferences: {
      sleepingHabits: 'Varies due to shifts',
      cleanliness: 'Very Neat',
      socialHabits: 'Introvert',
      smoking: 'Non-smoker',
      drinking: 'Rarely',
      schedule: 'Irregular',
      noiseTolerance: 'Low',
      diet: 'Vegetarian',
      pets: 'No Pets',
      security: 'High Priority',
    },
    compatibilityScores: {},
  },
  {
    id: '13',
    name: 'Ethan Morris',
    age: 24,
    gender: 'Male',
    occupation: 'Startup Founder',
    avatar: 'https://i.pravatar.cc/150?img=15',
    bio: 'Entrepreneur building a tech startup. Works odd hours but is respectful and tidy.',
    budget: 1200,
    location: 'Brooklyn',
    preferences: {
      sleepingHabits: 'Night Owl',
      cleanliness: 'Neat',
      socialHabits: 'Balanced',
      smoking: 'Non-smoker',
      drinking: 'Social Drinker',
      schedule: 'Flexible',
      noiseTolerance: 'Medium',
      diet: 'No Preference',
      pets: 'OK with pets',
      security: 'Medium Priority',
    },
    compatibilityScores: {},
  },
  {
    id: '14',
    name: 'Maya Thompson',
    age: 27,
    gender: 'Female',
    occupation: 'Yoga Instructor',
    avatar: 'https://i.pravatar.cc/150?img=2',
    bio: 'Yoga instructor who practices meditation daily. Peaceful, clean, and health-conscious.',
    budget: 1000,
    location: 'Brooklyn',
    preferences: {
      sleepingHabits: 'Early Riser',
      cleanliness: 'Very Neat',
      socialHabits: 'Balanced',
      smoking: 'Non-smoker',
      drinking: 'Rarely',
      schedule: 'Flexible',
      noiseTolerance: 'Low',
      diet: 'Vegan',
      pets: 'Loves Pets',
      security: 'Medium Priority',
    },
    compatibilityScores: {},
  },
  {
    id: '15',
    name: 'Daniel Garcia',
    age: 28,
    gender: 'Male',
    occupation: 'Photographer',
    avatar: 'https://i.pravatar.cc/150?img=16',
    bio: 'Freelance photographer who travels frequently. Easygoing and adaptable roommate.',
    budget: 1100,
    location: 'Manhattan',
    preferences: {
      sleepingHabits: 'Varies',
      cleanliness: 'Average',
      socialHabits: 'Extrovert',
      smoking: 'Outside Only',
      drinking: 'Social Drinker',
      schedule: 'Flexible',
      noiseTolerance: 'High',
      diet: 'No Preference',
      pets: 'OK with pets',
      security: 'Medium Priority',
    },
    compatibilityScores: {},
  },
  {
    id: '16',
    name: 'Rachel Wong',
    age: 26,
    gender: 'Female',
    occupation: 'Journalist',
    avatar: 'https://i.pravatar.cc/150?img=10',
    bio: 'Writer who needs some quiet time for work but enjoys socializing too. Clean and considerate.',
    budget: 1200,
    location: 'Brooklyn',
    preferences: {
      sleepingHabits: 'Regular Hours',
      cleanliness: 'Neat',
      socialHabits: 'Balanced',
      smoking: 'Non-smoker',
      drinking: 'Occasional',
      schedule: 'Flexible',
      noiseTolerance: 'Medium',
      diet: 'No Preference',
      pets: 'OK with pets',
      security: 'Medium Priority',
    },
    compatibilityScores: {},
  },
  {
    id: '17',
    name: 'Brandon Thomas',
    age: 25,
    gender: 'Male',
    occupation: 'Physical Therapist',
    avatar: 'https://i.pravatar.cc/150?img=17',
    bio: 'Healthcare professional who enjoys fitness and outdoor activities. Clean and organized.',
    budget: 1300,
    location: 'Queens',
    preferences: {
      sleepingHabits: 'Early Riser',
      cleanliness: 'Very Neat',
      socialHabits: 'Balanced',
      smoking: 'Non-smoker',
      drinking: 'Occasional',
      schedule: 'Regular 9-5',
      noiseTolerance: 'Medium',
      diet: 'No Preference',
      pets: 'No Pets',
      security: 'High Priority',
    },
    compatibilityScores: {},
  },
  {
    id: '18',
    name: 'Nina Barnes',
    age: 23,
    gender: 'Female',
    occupation: 'Art Student',
    avatar: 'https://i.pravatar.cc/150?img=19',
    bio: 'Art student who needs space for projects. Creative, friendly, and respectful of shared spaces.',
    budget: 850,
    location: 'Brooklyn',
    preferences: {
      sleepingHabits: 'Night Owl',
      cleanliness: 'Average',
      socialHabits: 'Extrovert',
      smoking: 'Outside Only',
      drinking: 'Social Drinker',
      schedule: 'Student Schedule',
      noiseTolerance: 'High',
      diet: 'Vegetarian',
      pets: 'Loves Pets',
      security: 'Medium Priority',
    },
    compatibilityScores: {},
  },
  {
    id: '19',
    name: 'Jason Kim',
    age: 29,
    gender: 'Male',
    occupation: 'Data Scientist',
    avatar: 'https://i.pravatar.cc/150?img=18',
    bio: 'Tech professional who works regular hours and enjoys board games and reading.',
    budget: 1400,
    location: 'Manhattan',
    preferences: {
      sleepingHabits: 'Regular Hours',
      cleanliness: 'Neat',
      socialHabits: 'Introvert',
      smoking: 'Non-smoker',
      drinking: 'Rarely',
      schedule: 'Regular 9-5',
      noiseTolerance: 'Low',
      diet: 'No Preference',
      pets: 'No Pets',
      security: 'High Priority',
    },
    compatibilityScores: {},
  },
  {
    id: '20',
    name: 'Leila Ramirez',
    age: 27,
    gender: 'Female',
    occupation: 'Event Planner',
    avatar: 'https://i.pravatar.cc/150?img=20',
    bio: 'Creative professional who loves to host small gatherings. Social but respectful of personal space.',
    budget: 1150,
    location: 'Brooklyn',
    preferences: {
      sleepingHabits: 'Regular Hours',
      cleanliness: 'Very Neat',
      socialHabits: 'Extrovert',
      smoking: 'Non-smoker',
      drinking: 'Social Drinker',
      schedule: 'Irregular',
      noiseTolerance: 'Medium',
      diet: 'No Preference',
      pets: 'OK with pets',
      security: 'Medium Priority',
    },
    compatibilityScores: {},
  },
];

export const compatibilityQuestions = [
  {
    id: 'sleeping',
    question: 'What are your sleeping habits?',
    options: [
      { value: 'early_riser', label: 'Early Riser (Before 7 AM)' },
      { value: 'regular', label: 'Regular Hours (7-9 AM)' },
      { value: 'night_owl', label: 'Night Owl (Sleep after midnight)' },
      { value: 'varies', label: 'Varies due to my schedule' },
    ],
  },
  {
    id: 'cleanliness',
    question: 'How would you describe your cleanliness level?',
    options: [
      { value: 'very_neat', label: 'Very Neat and Organized' },
      { value: 'neat', label: 'Generally Neat' },
      { value: 'average', label: 'Average Cleanliness' },
      { value: 'relaxed', label: 'Relaxed about Cleanliness' },
    ],
  },
  {
    id: 'social',
    question: 'How social are you at home?',
    options: [
      { value: 'introvert', label: 'Prefer Quiet & Privacy' },
      { value: 'balanced', label: 'Balanced - Sometimes Social, Sometimes Not' },
      { value: 'extrovert', label: 'Very Social & Enjoy Company' },
      { value: 'varies', label: 'Depends on the Day' },
    ],
  },
  {
    id: 'smoking',
    question: 'What is your stance on smoking?',
    options: [
      { value: 'non_smoker', label: 'Non-smoker & prefer non-smoking environment' },
      { value: 'outside_only', label: 'Non-smoker but ok with smoking outside' },
      { value: 'occasional', label: 'Occasional smoker (outside only)' },
      { value: 'smoker', label: 'Regular smoker' },
    ],
  },
  {
    id: 'drinking',
    question: 'What are your drinking habits?',
    options: [
      { value: 'none', label: 'Don\'t drink at all' },
      { value: 'rarely', label: 'Rarely drink' },
      { value: 'social', label: 'Social drinker (weekends/events)' },
      { value: 'regular', label: 'Regular drinker' },
    ],
  },
  {
    id: 'schedule',
    question: 'What is your typical daily schedule?',
    options: [
      { value: 'regular', label: 'Regular 9-5 work hours' },
      { value: 'flexible', label: 'Flexible/Remote work' },
      { value: 'student', label: 'Student schedule with classes' },
      { value: 'shifts', label: 'Rotating/Night shifts' },
    ],
  },
  {
    id: 'budget',
    question: 'What is your monthly budget for rent?',
    options: [
      { value: 'low', label: '$500-$800' },
      { value: 'medium', label: '$800-$1,200' },
      { value: 'high', label: '$1,200-$1,500' },
      { value: 'luxury', label: '$1,500+' },
    ],
  },
  {
    id: 'noise',
    question: 'What is your noise tolerance level?',
    options: [
      { value: 'low', label: 'Need quiet environment most of the time' },
      { value: 'medium', label: 'Can tolerate some noise' },
      { value: 'high', label: 'Very tolerant of noise' },
      { value: 'varies', label: 'Depends on time of day' },
    ],
  },
  {
    id: 'diet',
    question: 'Do you have dietary preferences?',
    options: [
      { value: 'none', label: 'No specific preferences' },
      { value: 'vegetarian', label: 'Vegetarian' },
      { value: 'vegan', label: 'Vegan' },
      { value: 'other', label: 'Other dietary restrictions' },
    ],
  },
  {
    id: 'pets',
    question: 'What is your preference regarding pets?',
    options: [
      { value: 'love', label: 'Love pets & have/want them' },
      { value: 'ok', label: 'OK with pets but don\'t have any' },
      { value: 'allergic', label: 'Allergic to some pets' },
      { value: 'no_pets', label: 'Prefer no pets' },
    ],
  },
];
