
import { RoommateProfile, Property } from './data';

export const indianRoommates: RoommateProfile[] = [
  {
    id: "ir1",
    name: "Rahul Sharma",
    age: 24,
    gender: "Male",
    occupation: "Software Engineer",
    location: "Bangalore, Karnataka",
    bio: "Tech enthusiast working at a startup. I'm a clean and organized person who respects others' privacy. I enjoy coding, reading, and occasional gaming.",
    budget: 15000,
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    compatibilityScores: {},
    preferences: {
      sleepingHabits: "Night owl (10pm-2am)",
      cleanliness: "Very clean and organized",
      socialHabits: "Occasionally social, respects privacy",
      smoking: "Non-smoker",
      drinking: "Social drinker",
      schedule: "9-5 work schedule with occasional weekend outings",
      noiseTolerance: "Moderate, no loud music after 10pm",
      diet: "Vegetarian",
      pets: "No pets",
      security: "High priority, careful with locks and security"
    }
  },
  {
    id: "ir2",
    name: "Priya Patel",
    age: 26,
    gender: "Female",
    occupation: "HR Professional",
    location: "Mumbai, Maharashtra",
    bio: "Working professional who loves to cook and travel. Looking for a clean and peaceful living space with like-minded people. I prefer a place closer to my office in BKC.",
    budget: 18000,
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    compatibilityScores: {},
    preferences: {
      sleepingHabits: "Early riser (5am-6am)",
      cleanliness: "Very clean and organized",
      socialHabits: "Balanced, enjoys both social time and alone time",
      smoking: "Non-smoker",
      drinking: "Occasional drinker",
      schedule: "Regular 9-6 work hours",
      noiseTolerance: "Prefers quiet environment",
      diet: "Vegetarian",
      pets: "Loves pets but doesn't own any",
      security: "Very security conscious"
    }
  },
  {
    id: "ir3",
    name: "Vikram Singh",
    age: 29,
    gender: "Male",
    occupation: "Product Manager",
    location: "Gurgaon, Haryana",
    bio: "Tech product manager who enjoys fitness and outdoor activities. Looking for a convenient location with easy access to metro and basic amenities nearby.",
    budget: 20000,
    avatar: "https://randomuser.me/api/portraits/men/62.jpg",
    compatibilityScores: {},
    preferences: {
      sleepingHabits: "Regular (11pm-7am)",
      cleanliness: "Reasonably tidy",
      socialHabits: "Outgoing but respects personal space",
      smoking: "Non-smoker",
      drinking: "Social drinker",
      schedule: "Flexible work hours",
      noiseTolerance: "Moderate",
      diet: "Non-vegetarian",
      pets: "No preference",
      security: "Basic security concerns"
    }
  },
  {
    id: "ir4",
    name: "Anjali Gupta",
    age: 23,
    gender: "Female",
    occupation: "Medical Student",
    location: "Delhi, Delhi",
    bio: "Final year MBBS student. I spend most of my time studying or at the hospital. Looking for a quiet place to focus on my studies.",
    budget: 12000,
    avatar: "https://randomuser.me/api/portraits/women/66.jpg",
    compatibilityScores: {},
    preferences: {
      sleepingHabits: "Irregular due to hospital shifts",
      cleanliness: "Very clean",
      socialHabits: "Quiet and studious",
      smoking: "Non-smoker",
      drinking: "Non-drinker",
      schedule: "Irregular hospital shifts",
      noiseTolerance: "Needs quiet study environment",
      diet: "Vegetarian",
      pets: "No pets due to allergies",
      security: "High priority"
    }
  },
  {
    id: "ir5",
    name: "Arjun Nair",
    age: 27,
    gender: "Male",
    occupation: "Digital Marketing Specialist",
    location: "Pune, Maharashtra",
    bio: "Creative professional working in digital marketing. I enjoy photography, hiking, and trying new cafes around the city.",
    budget: 14000,
    avatar: "https://randomuser.me/api/portraits/men/42.jpg",
    compatibilityScores: {},
    preferences: {
      sleepingHabits: "Night owl",
      cleanliness: "Moderately clean",
      socialHabits: "Very social and outgoing",
      smoking: "Smokes occasionally",
      drinking: "Social drinker",
      schedule: "Flexible work hours",
      noiseTolerance: "High tolerance",
      diet: "Non-vegetarian",
      pets: "Loves pets",
      security: "Standard security concerns"
    }
  },
  {
    id: "ir6",
    name: "Kavya Reddy",
    age: 25,
    gender: "Female",
    occupation: "Software Developer",
    location: "Hyderabad, Telangana",
    bio: "Backend developer working with a multinational tech company. I'm a minimalist who enjoys reading and practicing yoga in my free time.",
    budget: 16000,
    avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    compatibilityScores: {},
    preferences: {
      sleepingHabits: "Early riser (6am)",
      cleanliness: "Very clean and organized",
      socialHabits: "Introverted but friendly",
      smoking: "Non-smoker",
      drinking: "Occasional drinker",
      schedule: "Regular 9-5 work hours",
      noiseTolerance: "Prefers quiet environment",
      diet: "Vegetarian",
      pets: "No pets",
      security: "Very security conscious"
    }
  },
  {
    id: "ir7",
    name: "Rohan Joshi",
    age: 30,
    gender: "Male",
    occupation: "Financial Analyst",
    location: "Mumbai, Maharashtra",
    bio: "Finance professional working in investment banking. I'm organized and prefer a clean living space. I enjoy watching cricket and playing chess.",
    budget: 25000,
    avatar: "https://randomuser.me/api/portraits/men/52.jpg",
    compatibilityScores: {},
    preferences: {
      sleepingHabits: "Regular (11pm-7am)",
      cleanliness: "Very clean",
      socialHabits: "Balanced social life",
      smoking: "Non-smoker",
      drinking: "Social drinker",
      schedule: "Long work hours (9am-8pm)",
      noiseTolerance: "Moderate",
      diet: "Non-vegetarian",
      pets: "No pets",
      security: "High priority"
    }
  },
  {
    id: "ir8",
    name: "Neha Kapoor",
    age: 24,
    gender: "Female",
    occupation: "UI/UX Designer",
    location: "Bangalore, Karnataka",
    bio: "Creative designer looking for a place with good natural light. I'm a foodie and love trying new recipes on weekends.",
    budget: 17000,
    avatar: "https://randomuser.me/api/portraits/women/29.jpg",
    compatibilityScores: {},
    preferences: {
      sleepingHabits: "Regular (11pm-7am)",
      cleanliness: "Clean but not obsessive",
      socialHabits: "Social and enjoys hosting small gatherings",
      smoking: "Non-smoker",
      drinking: "Social drinker",
      schedule: "Flexible work hours",
      noiseTolerance: "Moderate",
      diet: "Vegetarian",
      pets: "Loves pets",
      security: "Standard security concerns"
    }
  },
  {
    id: "ir9",
    name: "Aditya Mehta",
    age: 28,
    gender: "Male",
    occupation: "Architect",
    location: "Ahmedabad, Gujarat",
    bio: "Creative architect who appreciates well-designed spaces. I enjoy sketching, visiting historical sites, and playing the guitar occasionally.",
    budget: 14000,
    avatar: "https://randomuser.me/api/portraits/men/78.jpg",
    compatibilityScores: {},
    preferences: {
      sleepingHabits: "Regular (11pm-7am)",
      cleanliness: "Organized and tidy",
      socialHabits: "Balanced, enjoys meaningful conversations",
      smoking: "Non-smoker",
      drinking: "Occasional drinker",
      schedule: "Standard work hours with occasional late nights",
      noiseTolerance: "Moderate",
      diet: "Vegetarian",
      pets: "No pets",
      security: "Basic security concerns"
    }
  },
  {
    id: "ir10",
    name: "Meera Iyer",
    age: 26,
    gender: "Female",
    occupation: "Content Writer",
    location: "Chennai, Tamil Nadu",
    bio: "Freelance writer who works from home. I'm looking for a peaceful environment where I can focus. I enjoy reading, writing, and occasional movie nights.",
    budget: 13000,
    avatar: "https://randomuser.me/api/portraits/women/83.jpg",
    compatibilityScores: {},
    preferences: {
      sleepingHabits: "Night owl",
      cleanliness: "Clean and organized",
      socialHabits: "Introverted but friendly",
      smoking: "Non-smoker",
      drinking: "Rarely drinks",
      schedule: "Works from home with flexible hours",
      noiseTolerance: "Needs quiet for work",
      diet: "Vegetarian",
      pets: "Loves cats",
      security: "Standard security concerns"
    }
  },
  {
    id: "ir11",
    name: "Samir Khan",
    age: 25,
    gender: "Male",
    occupation: "Data Scientist",
    location: "Pune, Maharashtra",
    bio: "Tech professional specialized in data science. I enjoy solving complex problems and exploring new technologies. I'm a fitness enthusiast and practice meditation regularly.",
    budget: 18000,
    avatar: "https://randomuser.me/api/portraits/men/33.jpg",
    compatibilityScores: {},
    preferences: {
      sleepingHabits: "Early riser (5:30am)",
      cleanliness: "Very clean and organized",
      socialHabits: "Balanced social life",
      smoking: "Non-smoker",
      drinking: "Occasional drinker",
      schedule: "Regular 9-6 work hours",
      noiseTolerance: "Moderate",
      diet: "Non-vegetarian",
      pets: "No preference",
      security: "Security conscious"
    }
  },
  {
    id: "ir12",
    name: "Divya Menon",
    age: 27,
    gender: "Female",
    occupation: "CA",
    location: "Kochi, Kerala",
    bio: "Chartered Accountant working with a consulting firm. I'm organized and value cleanliness. I enjoy cooking Kerala cuisine and watching Malayalam movies.",
    budget: 15000,
    avatar: "https://randomuser.me/api/portraits/women/7.jpg",
    compatibilityScores: {},
    preferences: {
      sleepingHabits: "Regular (10pm-6am)",
      cleanliness: "Very clean",
      socialHabits: "Moderately social",
      smoking: "Non-smoker",
      drinking: "Non-drinker",
      schedule: "Regular office hours with busy season overtime",
      noiseTolerance: "Prefers quiet environment",
      diet: "Non-vegetarian",
      pets: "No pets",
      security: "Very security conscious"
    }
  },
  {
    id: "ir13",
    name: "Varun Naidu",
    age: 24,
    gender: "Male",
    occupation: "Graphic Designer",
    location: "Bangalore, Karnataka",
    bio: "Creative professional who loves art and design. I'm looking for an apartment with other creative individuals. I enjoy music, movies, and visiting art galleries.",
    budget: 16000,
    avatar: "https://randomuser.me/api/portraits/men/56.jpg",
    compatibilityScores: {},
    preferences: {
      sleepingHabits: "Night owl",
      cleanliness: "Moderately clean",
      socialHabits: "Very social and outgoing",
      smoking: "Smokes occasionally",
      drinking: "Social drinker",
      schedule: "Flexible work hours",
      noiseTolerance: "High tolerance",
      diet: "No specific preference",
      pets: "Loves pets",
      security: "Basic security concerns"
    }
  },
  {
    id: "ir14",
    name: "Ananya Banerjee",
    age: 29,
    gender: "Female",
    occupation: "College Professor",
    location: "Kolkata, West Bengal",
    bio: "Literature professor who values intellectual conversations. I'm looking for a peaceful place where I can read and grade papers. I enjoy classical music and poetry.",
    budget: 17000,
    avatar: "https://randomuser.me/api/portraits/women/48.jpg",
    compatibilityScores: {},
    preferences: {
      sleepingHabits: "Regular (10pm-6am)",
      cleanliness: "Clean and organized",
      socialHabits: "Quiet and intellectual",
      smoking: "Non-smoker",
      drinking: "Occasional drinker",
      schedule: "Academic schedule with regular hours",
      noiseTolerance: "Prefers quiet environment",
      diet: "Vegetarian",
      pets: "No pets",
      security: "Standard security concerns"
    }
  },
  {
    id: "ir15",
    name: "Rishi Malhotra",
    age: 26,
    gender: "Male",
    occupation: "Bank Officer",
    location: "Delhi, Delhi",
    bio: "Banking professional who values discipline and organization. I'm looking for a place close to the metro for easy commute. I enjoy watching cricket and reading fiction.",
    budget: 15000,
    avatar: "https://randomuser.me/api/portraits/men/72.jpg",
    compatibilityScores: {},
    preferences: {
      sleepingHabits: "Early riser (6am)",
      cleanliness: "Very clean",
      socialHabits: "Moderately social",
      smoking: "Non-smoker",
      drinking: "Occasional drinker",
      schedule: "Regular 10-6 bank hours",
      noiseTolerance: "Moderate",
      diet: "Non-vegetarian",
      pets: "No pets",
      security: "Very security conscious"
    }
  },
  {
    id: "ir16",
    name: "Lakshmi Rao",
    age: 23,
    gender: "Female",
    occupation: "Research Assistant",
    location: "Hyderabad, Telangana",
    bio: "Research assistant at a biotechnology institute. I'm focused on my work and studies. I enjoy classical dance and visiting historical sites.",
    budget: 12000,
    avatar: "https://randomuser.me/api/portraits/women/54.jpg",
    compatibilityScores: {},
    preferences: {
      sleepingHabits: "Regular (10pm-6am)",
      cleanliness: "Very clean",
      socialHabits: "Quiet and studious",
      smoking: "Non-smoker",
      drinking: "Non-drinker",
      schedule: "Regular lab hours (9am-5pm)",
      noiseTolerance: "Needs quiet for study",
      diet: "Vegetarian",
      pets: "No pets",
      security: "High priority"
    }
  },
  {
    id: "ir17",
    name: "Amit Choudhary",
    age: 31,
    gender: "Male",
    occupation: "Sales Manager",
    location: "Mumbai, Maharashtra",
    bio: "Sales professional who travels frequently for work. I'm looking for a place where I can relax when I'm not traveling. I enjoy watching football and trying new restaurants.",
    budget: 22000,
    avatar: "https://randomuser.me/api/portraits/men/21.jpg",
    compatibilityScores: {},
    preferences: {
      sleepingHabits: "Varies due to travel",
      cleanliness: "Clean but not obsessive",
      socialHabits: "Outgoing and social",
      smoking: "Non-smoker",
      drinking: "Social drinker",
      schedule: "Irregular due to travel",
      noiseTolerance: "High tolerance",
      diet: "Non-vegetarian",
      pets: "No preference",
      security: "High priority due to travel"
    }
  },
  {
    id: "ir18",
    name: "Shreya Verma",
    age: 25,
    gender: "Female",
    occupation: "Dentist",
    location: "Chandigarh, Punjab",
    bio: "Healthcare professional who values cleanliness and hygiene. I'm looking for a place close to my clinic. I enjoy cooking and yoga in my free time.",
    budget: 16000,
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
    compatibilityScores: {},
    preferences: {
      sleepingHabits: "Early riser (5:30am)",
      cleanliness: "Extremely clean",
      socialHabits: "Balanced social life",
      smoking: "Non-smoker",
      drinking: "Rarely drinks",
      schedule: "Regular clinic hours (10am-7pm)",
      noiseTolerance: "Prefers quiet environment",
      diet: "Vegetarian",
      pets: "No pets due to allergies",
      security: "High priority"
    }
  },
  {
    id: "ir19",
    name: "Rajiv Kumar",
    age: 28,
    gender: "Male",
    occupation: "Civil Engineer",
    location: "Jaipur, Rajasthan",
    bio: "Engineering professional working on various construction projects. I'm looking for a place with good connectivity. I enjoy playing chess and watching documentaries.",
    budget: 14000,
    avatar: "https://randomuser.me/api/portraits/men/45.jpg",
    compatibilityScores: {},
    preferences: {
      sleepingHabits: "Regular (11pm-7am)",
      cleanliness: "Reasonably tidy",
      socialHabits: "Moderately social",
      smoking: "Non-smoker",
      drinking: "Occasional drinker",
      schedule: "Regular office hours with occasional site visits",
      noiseTolerance: "Moderate",
      diet: "Vegetarian",
      pets: "No preference",
      security: "Standard security concerns"
    }
  },
  {
    id: "ir20",
    name: "Deepika Agarwal",
    age: 26,
    gender: "Female",
    occupation: "Marketing Executive",
    location: "Bangalore, Karnataka",
    bio: "Marketing professional who enjoys a balance between work and personal life. I'm a foodie and love exploring new cafes and restaurants around the city.",
    budget: 18000,
    avatar: "https://randomuser.me/api/portraits/women/36.jpg",
    compatibilityScores: {},
    preferences: {
      sleepingHabits: "Regular (11pm-7am)",
      cleanliness: "Clean and organized",
      socialHabits: "Outgoing and social",
      smoking: "Non-smoker",
      drinking: "Social drinker",
      schedule: "Regular 9-6 work hours",
      noiseTolerance: "Moderate",
      diet: "Non-vegetarian",
      pets: "Loves pets",
      security: "Standard security concerns"
    }
  }
];

export const indianProperties: Property[] = [
  {
    id: "ip1",
    title: "Modern 3BHK Apartment in Koramangala",
    description: "Spacious 3-bedroom apartment in a gated community with 24/7 security, gym, and swimming pool. Fully furnished with modern amenities and close to tech parks.",
    location: "Koramangala, Bangalore",
    price: 35000,
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YXBhcnRtZW50fGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    roomType: "private",
    amenities: ["Fully Furnished", "Air Conditioning", "Gym", "Swimming Pool", "Power Backup", "Lift", "Security", "Parking"],
    nearbyFacilities: ["Tech Parks", "Restaurants", "Hospitals", "Shopping Malls"],
    ownerContact: "owner_koramangala@email.com",
    availableFrom: "2023-12-01",
    virtualTourUrl: "https://youtu.be/example_tour1"
  },
  {
    id: "ip2",
    title: "1BHK Apartment in Powai",
    description: "Cozy 1-bedroom apartment in a residential complex. Semi-furnished with basic amenities and close to IIT Bombay and Hiranandani Business Park.",
    location: "Powai, Mumbai",
    price: 25000,
    imageUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YXBhcnRtZW50fGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    roomType: "private",
    amenities: ["Semi-Furnished", "Air Conditioning", "Security", "Parking"],
    nearbyFacilities: ["IIT Bombay", "Hiranandani Business Park", "Restaurants", "D-Mart"],
    ownerContact: "owner_powai@email.com",
    availableFrom: "2023-11-15",
    virtualTourUrl: "https://youtu.be/example_tour2"
  },
  {
    id: "ip3",
    title: "Single Room in 3BHK Flat",
    description: "Furnished single room available in a shared 3BHK apartment. Common kitchen and living area. Suitable for working professionals or students.",
    location: "Indira Nagar, Bangalore",
    price: 12000,
    imageUrl: "https://images.unsplash.com/photo-1494203484021-3c454daf695d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGJlZHJvb218ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    roomType: "shared",
    amenities: ["Furnished", "Wi-Fi", "Washing Machine", "Refrigerator", "Gas Connection"],
    nearbyFacilities: ["Metro Station", "Restaurants", "Pubs", "Grocery Stores"],
    ownerContact: "owner_indiranagar@email.com",
    availableFrom: "2023-11-01",
    virtualTourUrl: "https://youtu.be/example_tour3"
  },
  {
    id: "ip4",
    title: "2BHK Flat in DLF Phase 3",
    description: "Semi-furnished 2-bedroom apartment with modern amenities. Located in a prime location with good connectivity to major tech companies.",
    location: "DLF Phase 3, Gurgaon",
    price: 28000,
    imageUrl: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YXBhcnRtZW50JTIwbGl2aW5nJTIwcm9vbXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    roomType: "private",
    amenities: ["Semi-Furnished", "Air Conditioning", "Power Backup", "Security", "Parking", "Lift"],
    nearbyFacilities: ["Cyber City", "Metro Station", "Hospitals", "Shopping Malls"],
    ownerContact: "owner_dlf@email.com",
    availableFrom: "2023-12-15",
    virtualTourUrl: "https://youtu.be/example_tour4"
  },
  {
    id: "ip5",
    title: "PG Accommodation for Women",
    description: "Furnished rooms available in a women's PG with meals included. Safe and secure environment with CCTV surveillance.",
    location: "Ameerpet, Hyderabad",
    price: 9000,
    imageUrl: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aG9zdGVsfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    roomType: "shared",
    amenities: ["Furnished", "Food Included", "Wi-Fi", "Housekeeping", "CCTV", "Laundry"],
    nearbyFacilities: ["Training Institutes", "Metro Station", "Restaurants", "Medical Stores"],
    ownerContact: "owner_ameerpet@email.com",
    availableFrom: "2023-11-10",
    virtualTourUrl: null
  },
  {
    id: "ip6",
    title: "Luxury 3BHK Apartment in Anna Nagar",
    description: "High-end fully furnished apartment with premium amenities and modern interiors. Located in a prestigious neighborhood.",
    location: "Anna Nagar, Chennai",
    price: 40000,
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGx1eHVyeSUyMGFwYXJ0bWVudHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    roomType: "private",
    amenities: ["Fully Furnished", "Air Conditioning", "Gym", "Swimming Pool", "Club House", "Power Backup", "Lift", "Security", "Parking", "Indoor Games"],
    nearbyFacilities: ["Shopping Malls", "Hospitals", "Schools", "Restaurants"],
    ownerContact: "owner_annanagar@email.com",
    availableFrom: "2023-12-01",
    virtualTourUrl: "https://youtu.be/example_tour5"
  },
  {
    id: "ip7",
    title: "Single Room in Coliving Space",
    description: "Modern coliving space with private rooms and shared common areas. Includes all utilities and regular community events.",
    location: "HSR Layout, Bangalore",
    price: 15000,
    imageUrl: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y29saXZpbmd8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    roomType: "shared",
    amenities: ["Furnished", "Air Conditioning", "Wi-Fi", "House Keeping", "Laundry", "Community Events"],
    nearbyFacilities: ["Tech Parks", "Restaurants", "Supermarkets", "Bus Stand"],
    ownerContact: "owner_hsr@email.com",
    availableFrom: "2023-11-15",
    virtualTourUrl: "https://youtu.be/example_tour6"
  },
  {
    id: "ip8",
    title: "2BHK Independent House in Aundh",
    description: "Independent house with 2 bedrooms, kitchen, and living area. Suitable for family or group of friends. Peaceful neighborhood.",
    location: "Aundh, Pune",
    price: 22000,
    imageUrl: "https://images.unsplash.com/photo-1558036117-15d82a90b9b1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aG91c2UlMjBpbmRpYXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    roomType: "private",
    amenities: ["Semi-Furnished", "Garden", "Parking", "Water Purifier"],
    nearbyFacilities: ["IT Hubs", "Schools", "Hospitals", "Shopping Centers"],
    ownerContact: "owner_aundh@email.com",
    availableFrom: "2023-12-10",
    virtualTourUrl: null
  },
  {
    id: "ip9",
    title: "Shared Room in 2BHK Apartment",
    description: "Bed space available in a shared room in 2BHK apartment. Suitable for students or entry-level professionals.",
    location: "Laxmi Nagar, Delhi",
    price: 7000,
    imageUrl: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c2hhcmVkJTIwcm9vbXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    roomType: "shared",
    amenities: ["Bed", "Wi-Fi", "Washing Machine", "Gas Connection", "TV"],
    nearbyFacilities: ["Metro Station", "Coaching Centers", "Restaurants", "Market"],
    ownerContact: "owner_laxminagar@email.com",
    availableFrom: "2023-11-05",
    virtualTourUrl: null
  },
  {
    id: "ip10",
    title: "1BHK Flat near Salt Lake",
    description: "Compact 1-bedroom apartment ideal for small family or working professionals. Close to IT sector and good connectivity.",
    location: "Salt Lake, Kolkata",
    price: 16000,
    imageUrl: "https://images.unsplash.com/photo-1501183638710-841dd1904471?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aG9tZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    roomType: "private",
    amenities: ["Semi-Furnished", "Air Conditioning", "Security", "Parking"],
    nearbyFacilities: ["Sector V", "Shopping Malls", "Hospitals", "Bus Stand"],
    ownerContact: "owner_saltlake@email.com",
    availableFrom: "2023-12-01",
    virtualTourUrl: "https://youtu.be/example_tour7"
  },
  {
    id: "ip11",
    title: "Furnished Studio Apartment",
    description: "Compact studio apartment with modern amenities. Perfect for bachelor or young couple. Located in prime area with good connectivity.",
    location: "Vashi, Navi Mumbai",
    price: 18000,
    imageUrl: "https://images.unsplash.com/photo-1533779283484-8ad4940aa3a8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8c3R1ZGlvJTIwYXBhcnRtZW50fGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    roomType: "private",
    amenities: ["Fully Furnished", "Air Conditioning", "Wi-Fi Ready", "Security", "Lift"],
    nearbyFacilities: ["Railway Station", "Shopping Centers", "Hospitals", "Restaurants"],
    ownerContact: "owner_vashi@email.com",
    availableFrom: "2023-11-20",
    virtualTourUrl: "https://youtu.be/example_tour8"
  },
  {
    id: "ip12",
    title: "2BHK Apartment in Jayanagar",
    description: "Spacious 2-bedroom apartment in a peaceful residential area. Semi-furnished with good amenities and close to major facilities.",
    location: "Jayanagar, Bangalore",
    price: 25000,
    imageUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fGFwYXJ0bWVudHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    roomType: "private",
    amenities: ["Semi-Furnished", "Air Conditioning", "Power Backup", "Security", "Parking"],
    nearbyFacilities: ["Parks", "Shopping Complex", "Hospitals", "Schools"],
    ownerContact: "owner_jayanagar@email.com",
    availableFrom: "2023-12-05",
    virtualTourUrl: "https://youtu.be/example_tour9"
  },
  {
    id: "ip13",
    title: "Hostel for Students",
    description: "Affordable hostel accommodation with shared rooms. Includes meals and basic amenities. Safe environment with strict rules.",
    location: "Kota, Rajasthan",
    price: 8000,
    imageUrl: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c2hhcmVkJTIwcm9vbXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    roomType: "shared",
    amenities: ["Furnished", "Food Included", "Wi-Fi", "Study Room", "Laundry"],
    nearbyFacilities: ["Coaching Centers", "Libraries", "Stationary Shops", "Medical Stores"],
    ownerContact: "owner_kota@email.com",
    availableFrom: "2023-11-10",
    virtualTourUrl: null
  },
  {
    id: "ip14",
    title: "3BHK Luxury Villa",
    description: "Spacious villa with modern amenities and elegant interiors. Located in a gated community with excellent facilities.",
    location: "Whitefield, Bangalore",
    price: 50000,
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8dmlsbGF8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    roomType: "private",
    amenities: ["Fully Furnished", "Air Conditioning", "Private Garden", "Gym", "Swimming Pool", "Club House", "Security", "Parking"],
    nearbyFacilities: ["Tech Parks", "International Schools", "Hospitals", "Shopping Malls"],
    ownerContact: "owner_whitefield@email.com",
    availableFrom: "2023-12-15",
    virtualTourUrl: "https://youtu.be/example_tour10"
  },
  {
    id: "ip15",
    title: "1RK in Andheri West",
    description: "Compact 1RK apartment suitable for bachelor. Basic amenities provided and well-connected to public transport.",
    location: "Andheri West, Mumbai",
    price: 15000,
    imageUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8c21hbGwlMjBhcGFydG1lbnR8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    roomType: "private",
    amenities: ["Semi-Furnished", "Wi-Fi Ready", "Water Purifier"],
    nearbyFacilities: ["Railway Station", "Metro Station", "Markets", "Restaurants"],
    ownerContact: "owner_andheri@email.com",
    availableFrom: "2023-11-10",
    virtualTourUrl: null
  },
  {
    id: "ip16",
    title: "Co-living Space for Women",
    description: "Modern co-living space exclusively for women with furnished private rooms and shared common areas. Safe and secure environment.",
    location: "Electronic City, Bangalore",
    price: 13000,
    imageUrl: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y29saXZpbmd8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    roomType: "shared",
    amenities: ["Furnished", "Air Conditioning", "Wi-Fi", "House Keeping", "Laundry", "Security"],
    nearbyFacilities: ["Tech Parks", "Shopping Centers", "Hospitals", "Bus Stand"],
    ownerContact: "owner_electroniccity@email.com",
    availableFrom: "2023-11-15",
    virtualTourUrl: "https://youtu.be/example_tour11"
  },
  {
    id: "ip17",
    title: "2BHK Apartment in Banjara Hills",
    description: "Upscale 2-bedroom apartment in a premium locality. Well-furnished with quality amenities and serene environment.",
    location: "Banjara Hills, Hyderabad",
    price: 30000,
    imageUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YXBhcnRtZW50fGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    roomType: "private",
    amenities: ["Fully Furnished", "Air Conditioning", "Gym", "Security", "Parking", "Lift", "Power Backup"],
    nearbyFacilities: ["Hospitals", "Shopping Malls", "Restaurants", "Schools"],
    ownerContact: "owner_banjarahills@email.com",
    availableFrom: "2023-12-10",
    virtualTourUrl: "https://youtu.be/example_tour12"
  },
  {
    id: "ip18",
    title: "Affordable PG for Men",
    description: "Budget-friendly PG accommodation for men with basic amenities and meals included. Suitable for students and working bachelors.",
    location: "BTM Layout, Bangalore",
    price: 8500,
    imageUrl: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aG9zdGVsfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    roomType: "shared",
    amenities: ["Furnished", "Food Included", "Wi-Fi", "TV", "Washing Machine"],
    nearbyFacilities: ["Tech Parks", "Bus Stand", "Grocery Stores", "Restaurants"],
    ownerContact: "owner_btm@email.com",
    availableFrom: "2023-11-05",
    virtualTourUrl: null
  },
  {
    id: "ip19",
    title: "1BHK Flat in Ashok Nagar",
    description: "Well-maintained 1-bedroom apartment in central location. Good connectivity and nearby facilities.",
    location: "Ashok Nagar, Chennai",
    price: 17000,
    imageUrl: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YXBhcnRtZW50JTIwbGl2aW5nJTIwcm9vbXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    roomType: "private",
    amenities: ["Semi-Furnished", "Air Conditioning", "Power Backup", "Security"],
    nearbyFacilities: ["Metro Station", "Shopping Centers", "Hospitals", "Schools"],
    ownerContact: "owner_ashoknagar@email.com",
    availableFrom: "2023-11-25",
    virtualTourUrl: "https://youtu.be/example_tour13"
  },
  {
    id: "ip20",
    title: "2BHK Independent Floor",
    description: "Independent floor with 2 bedrooms in a residential area. Good for family with children. Peaceful surroundings.",
    location: "Vaishali, Ghaziabad",
    price: 20000,
    imageUrl: "https://images.unsplash.com/photo-1558036117-15d82a90b9b1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aG91c2UlMjBpbmRpYXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    roomType: "private",
    amenities: ["Semi-Furnished", "Power Backup", "Parking", "Water Purifier"],
    nearbyFacilities: ["Metro Station", "Schools", "Markets", "Hospitals"],
    ownerContact: "owner_vaishali@email.com",
    availableFrom: "2023-12-05",
    virtualTourUrl: null
  }
];
